// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.qcmoke.grpc.proto;

public interface UserDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 3;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 3;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>int32 age = 4;</code>
   */
  int getAge();

  /**
   * <code>string remark = 5;</code>
   */
  java.lang.String getRemark();
  /**
   * <code>string remark = 5;</code>
   */
  com.google.protobuf.ByteString
      getRemarkBytes();
}
