// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.qcmoke.grpc.proto;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();
}
